// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Claim struct {
	ID        uuid.UUID `json:"id"`
	NDC       string    `json:"ndc"`
	Quantity  int64     `json:"quantity"`
	NPI       string    `json:"npi"`
	Price     float64   `json:"price"`
	Timestamp time.Time `json:"timestamp"`
}

type Pharmacy struct {
	NPI       string    `json:"npi"`
	Chain     string    `json:"chain"`
	Timestamp time.Time `json:"timestamp"`
}

type Reversal struct {
	ID        uuid.UUID `json:"id"`
	ClaimID   uuid.UUID `json:"claim_id"`
	Timestamp time.Time `json:"timestamp"`
}
