// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Claim struct {
	ID        pgtype.UUID      `json:"id"`
	NDC       string           `json:"ndc"`
	Quantity  int32            `json:"quantity"`
	NPI       string           `json:"npi"`
	Price     pgtype.Numeric   `json:"price"`
	Timestamp pgtype.Timestamp `json:"timestamp"`
}

type Pharmacy struct {
	NPI   string `json:"npi"`
	Chain string `json:"chain"`
}

type Reversal struct {
	ID        pgtype.UUID      `json:"id"`
	ClaimID   pgtype.UUID      `json:"claim_id"`
	Timestamp pgtype.Timestamp `json:"timestamp"`
}
